FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /GraphQL
   
# copy source
COPY GraphQL.Simplify/. .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /GraphQL   
COPY --from=build /GraphQL/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "graph.simplify.api.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet GraphQL.Simplify.api.dll

ENTRYPOINT ["dotnet", "graph.simplify.api.dll"]